name: Deploy Azure Functions

on:
  push:
    paths:
    - 'IntervalFunction/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r IntervalFunction/requirements.txt
    
    - name: 'Run Azure Functions Action 1'
      uses: Azure/functions-action@v1
      id: fa1
      with:
        app-name: mlIntervalfunctionsss
        package: IntervalFunctions/Function1
        publish-profile: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE_mlIntervalfunctionsss }} 
        scm-do-build-during-deployment: true
        enable-oryx-build: true

    - name: 'Run Azure Functions Action 2'
      uses: Azure/functions-action@v1
      id: fa2
      with:
        app-name: mlIntervalfunctionsss2
        package: IntervalFunctions/Function2
        publish-profile: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE_mlIntervalfunctionsss2 }} 
        scm-do-build-during-deployment: true
        enable-oryx-build: true

    - name: 'Run Azure Functions Action 3'
      uses: Azure/functions-action@v1
      id: fa3
      with:
        app-name: mlIntervalfunctionsss3
        package: IntervalFunctions/Function3
        publish-profile: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE_mlIntervalfunctionsss3 }} 
        scm-do-build-during-deployment: true
        enable-oryx-build: true