name: Deploy Azure Functions

on:
  push:
    paths:
      - 'IntervalFunction/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: [mlIntervalfunctionsss, mlIntervalfunctionsss2, mlIntervalfunctionsss3]
        cron: ["0 0/15 * * * *", "5 0/15 * * * *", "10 0/15 * * * *"]

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
        python-version: '3.9'

     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r IntervalFunction/requirements.txt

     - name: Set CRON Schedule
       run: |
        sed -i "s|@app.timer_trigger(schedule=\"[^\"]*\"/@app.timer_trigger(schedule=\"${{ matrix.cron }}\"/g" IntervalFunction/function_app.py

     - name: Deploy to Azure Function App
       env:
            PUBLISH_PROFILE: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE_mlIntervalfunctionsss }}
       if: ${{ matrix.app_name == 'mlIntervalfunctionsss' }}
       run: |
            func azure functionapp publish mlIntervalfunctionsss --publish-profile "$PUBLISH_PROFILE"

     - name: Deploy to Azure Function App
       env:
        PUBLISH_PROFILE: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE_mlIntervalfunctionsss2 }}
       if: ${{ matrix.app_name == 'mlIntervalfunctionsss2' }}
       run: |
        func azure functionapp publish mlIntervalfunctionsss2 --publish-profile "$PUBLISH_PROFILE"

     - name: Deploy to Azure Function App
       env:
        PUBLISH_PROFILE: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE_mlIntervalfunctionsss3 }}
       if: ${{ matrix.app_name == 'mlIntervalfunctionsss3' }}
       run: |
        func azure functionapp publish mlIntervalfunctionsss3 --publish-profile "$PUBLISH_PROFILE"