name: Deploy Azure Functions

on:
  push:
    paths:
    - 'IntervalFunction/**'

jobs:
  setup-tools:
    runs-on: ubuntu-latest
    steps:
    - name: Install Azure Functions Core Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
        sudo apt-get update
        sudo apt-get install azure-functions-core-tools-4
        
    - name: Verify Azure Functions Core Tools Installation
      run: func --version

  deploy:
    needs: setup-tools  # Ensures the tools are installed before this job starts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: [mlIntervalfunctionsss, mlIntervalfunctionsss2, mlIntervalfunctionsss3]
        cron: ["0 0/15 * * * *", "5 0/15 * * * *", "10 0/15 * * * *"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r IntervalFunction/requirements.txt

    - name: Set CRON Schedule
      run: |
        sed -i "s|@app.timer_trigger(schedule=\"[^\"]*\"|@app.timer_trigger(schedule=\"${{ matrix.cron }}\"|g" IntervalFunction/function_app.py

    - name: Verify Azure Functions Core Tools Installation
      run: func --version

    - name: Set PUBLISH_PROFILE based on app_name
      id: set-secrets
      run: |
        if [[ "${{ matrix.app_name }}" == "mlIntervalfunctionsss" ]]; then
          echo "PUBLISH_PROFILE=${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE_mlIntervalfunctionsss }}" >> $GITHUB_ENV
        elif [[ "${{ matrix.app_name }}" == "mlIntervalfunctionsss2" ]]; then
          echo "PUBLISH_PROFILE=${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE_mlIntervalfunctionsss2 }}" >> $GITHUB_ENV
        elif [[ "${{ matrix.app_name }}" == "mlIntervalfunctionsss3" ]]; then
          echo "PUBLISH_PROFILE=${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE_mlIntervalfunctionsss3 }}" >> $GITHUB_ENV

    - name: Deploy to Azure Function App
      run: |
        pushd './IntervalFunction'
        func azure functionapp publish ${{ matrix.app_name }} --publish-profile "$PUBLISH_PROFILE"
        popd
